### ISSUE TITLE
kaleyra.addUserDetails not working on IOs with kaleyra.startCallFrom

### ISSUE THREAD

**Issue by nicmell** [KaleyraVideo/VideoReactNativeModule#1]
**Expected behavior**
Friendly user name is shown at the top of the screen call.

**Actual behavior**
UserID is shown instead.

**Step to reproduce:**
Initialize the kalerya instance with `configure` and authenticate the active user with a `connect`.
Later call:
```
userDetails = {nickName: 'nickName', userID: 'userID'}
kaleyra.addUsersDetails(userDetails);
kaleyra.startCallFrom(url);
```

**Environment**
iPhone 8 simulator, ios version: 14.2 (986.5)

**Comment by marcobrescianini-kaleyra** [comment]
Hi @nicmell we'll look into it and we'll get back to you asap

**Comment by nicmell** [comment]
Hello, I confirm that the workaround proposed by @alessandrolimardo is working.
Many thanks for for the support

**Comment by alessandrolimardo** [comment]
A new version (1.0.1) of this react native module has been released uniforming the user details format behaviour between all platforms.
